apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: $image
        name: nginx
        ports:
        - containerPort: 8080
          protocol: TCP
          name: 8080-tcp
