FROM projectatomic/atomicapp:0.2.2

MAINTAINER Aaron Weitekamp <aweiteka@redhat.com>

LABEL io.projectatomic.nulecule.providers="openshift,docker" \
      io.projectatomic.nulecule.specversion="0.0.2"

ADD /Nulecule /Dockerfile README.md /application-entity/
ADD /artifacts /application-entity/artifacts
