apiVersion: v1
kind: Service
metadata:
  labels:
    app: nonroot-nginx
  name: nonroot-nginx
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: nonroot-nginx
    deploymentconfig: nonroot-nginx
  type: ClusterIP
status:
  loadBalancer: {}
