apiVersion: v1
kind: Template
metadata:
  name: nginx-template
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: nginx
    name: nginx
  spec:
    replicas: 1
    selector:
      app: nginx
      deploymentconfig: nginx
    template:
      metadata:
        labels:
          app: nginx
          deploymentconfig: nginx
      spec:
        containers:
        - image: $image
          name: nginx
          ports:
          - containerPort: 8080
            name: 8080-tcp
            protocol: TCP
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: nginx
    name: nginx
  spec:
    ports:
    - name: 8080-tcp
      port: $hostport
      protocol: TCP
      targetPort: 8080
    selector:
      app: nginx
      deploymentconfig: nginx
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: nginx
    name: nginx
  spec:
    port:
      targetPort: 8080
    to:
      kind: Service
      name: nginx
